# Generated by Django 4.0.2 on 2022-02-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='author',
            new_name='Authors',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='name',
            new_name='book',
        ),
    ]
