# Generated by Django 4.0.2 on 2022-02-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0002_rename_author_authors_rename_name_books_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='released_at',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
