# Generated by Django 4.0.2 on 2022-02-11 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0003_alter_books_released_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='author_name',
        ),
        migrations.AddField(
            model_name='books',
            name='authors_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutorial.authors'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
