# Generated by Django 4.0.2 on 2022-02-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0006_rename_author_author_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authors_id',
            new_name='author',
        ),
    ]
