# Generated by Django 4.0.2 on 2022-02-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0009_remove_author_id_remove_book_author_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='uuid',
            new_name='id',
        ),
    ]
