# Generated by Django 4.0.2 on 2022-02-17 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0013_remove_author_id_remove_book_id_author_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.UUIDField(default=uuid.UUID('4e23a695-bd8b-419b-a928-6681edd1dbcf'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.UUIDField(default=uuid.UUID('bad0dd1a-8ef4-4416-964a-4ca30fd5c147'), editable=False, primary_key=True, serialize=False),
        ),
    ]
